### ISSUE TITLE
help_with_some_C++_loop

### ISSUE THREAD

**Issue by Holow-man** [Holow-man/H.M-n#1]
"Hey,

I'm a beginner in the GitHub community, so if I do something wrong, please give me feedback.

I am currently learning C++ loops and have discovered an issue: if the iterator ii is below 1,000,000,000, the program works fine, but if I add another zero, the loop doesn't work properly.

Can you explain to me where the issue might be?"

#include <iostream>

using namespace std;

int bacteria=1, time=0;

int main()
{
    for (int i=1; i<=1000000000; i=i*2) //bacteria as ITERATOR
    {
        cout<<"Amount of bacteria: "<<i<<endl;
        bacteria=bacteria * 2;
        cout<<"Time passt: " <<czas++<<endl;
    }
    return 0;

**Comment by vil02** [comment]
On most of the platforms `int` has 32 bits. `1000000000` _fits_ into 32 bits and `10000000000` does not ([some python code](https://www.online-python.com/O5gxitWGQ1) showing that). Depending on the configuration of the compiler you might get some overflow warning. Please have a look: https://godbolt.org/z/fWG57saMx.

You can use another type to store your variables. Maybe `unsigned long long` or [`std::uint64_t`](https://en.cppreference.com/w/cpp/types/integer).

**Comment by Holow-man** [comment]
Thank you for explaining and helping. I know the problem is kind of fiddling, but still, good to know.
